branches:
  only:
    - master
language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
before_script:
  - npm run test:db-deploy
script: npm run test:cover && npm run test:coveralls
